### ISSUE TITLE
When validate digger config yaml we should want users if there are any unused parameters

### ISSUE THREAD

**Issue by veziak** [diggerhq/lib-digger-config#34]
for example in the following config 'plan' will be just ignored, but user could expect that it affect something
```
projects:
- name: dev
  dir: terraform/dev
  workflow: default
  plan:
```
